name: CI Workflow
on: [push]

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository in ubuntu's file system 
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Print contents in current directory
        run: ls -la
      - name: Unit tests
        run: ./gradlew testDebugUnitTest

